logging:
  level:
    de.daniel.marlinghaus: DEBUG
trivy:
  tmp-directory: "/appl/tmp/trivy-client"
  host: "http://localhost:9000"
  bin-directory: "/appl/repo/trivy-rest-client/trivy"
springdoc:
  api-docs:
    enabled: true
    path: "/docs"
  swagger-ui:
    path: "/docs/ui"
    enabled: true
    disable-swagger-default-url: true
#management:
#  server:
#    port: 8081
#server:
#  port: 8081
